name: ToDoApp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 6.1.0
  flutter_svg: 2.0.9
  intl: 0.18.1
  firebase_core: 2.24.2
  firebase_auth: 4.16.0
  cloud_firestore: 4.14.0
  image_picker: 1.0.7
  firebase_storage: 11.6.0
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/todoapp.png"

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

